Part A

Q.1

In [2]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])


arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])


print(arr1[2])       
print(arr1[1:4])    
print(arr2[1, 2])     
print(arr2[0])        
print(arr2[:, 1])    
print(arr2[0:2, 1:3])

30
[20 30 40]
6
[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


Q.2

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


print(a + b)   
print(a - b)   
print(a * b)   

print(np.mean(a))
print(np.var(a))
print(np.std(a))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
2.0
0.6666666666666666
0.816496580927726


Q.3

In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr1 = np.array([10, 20, 30])

print(arr2 + arr1)

print(arr2 * 2)

vec = np.array([1, 2, 3])
print(arr2 * vec)



[[11 22 33]
 [14 25 36]]


- NumPy automatically adjusts smaller arrays
- It stretches dimensions where needed
- No extra memory is actually copied (efficient)

Q.4

In [ ]:
arr = np.array([-2, -1, 0, 1, 2, 3])
print(arr ** 2)
print(arr ** 3)

arr[arr < 0] = 0
print(arr)

arr[arr < 0] = 0
print(arr)


arr = np.array([10, 20, 30, 40])

norm = (arr - arr.min()) / (arr.max() - arr.min())
print(norm)

Q.5

In [ ]:
data = np.array([[10, 50, 30],
                 [20, 60, 40],
                 [70, 80, 90]])

flat = data.flatten()
top5 = np.sort(flat)[-5:]
print(top5)

print(np.sum(data, axis=1)) 
print(np.sum(data, axis=0))  

threshold = 50
indices = np.where(data > threshold)
print(indices)

Part B

1. Matrix Operations using NumPy

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)

print(result)

print(A.T)

det = np.linalg.det(A)
print(det)






In [ ]:
A = np.array([[2, 1],
              [1, 1]])

B = np.array([5, 3])

solution = np.linalg.solve(A, B)
print(solution)

In [ ]:
import time

arr = list(range(1000000))

start = time.time()

total = 0
for i in arr:
    total += i

end = time.time()

print("Loop Time:", end - start)

In [ ]:
arr_np = np.arange(1000000)

start = time.time()

total = np.sum(arr_np)

end = time.time()

print("NumPy Time:", end - start)

NumPy is much faster than Python loops
Loop takes more time because it processes element by element
NumPy uses vectorized operations and optimized C code internally

Part C

Q1
NumPy broadcasting is a technique that allows us to perform operations on arrays of different shapes without manually resizing them.
In simple words, NumPy automatically expands the smaller array so that both arrays have compatible shapes.

Why it is useful:
- No need to write loops
- Code becomes shorter and cleaner
- Faster execution
- Saves memory

Q.2 
import numpy as np
def normalize(X):
    X = np.array(X)
    return (X - X.min()) / (X.max() - X.min())

Q.3
Vectorisation and loops are two different ways of performing operations on data. 
In loops, elements are processed one by one using a for loop, which makes the execution slower because Python handles each iteration separately. 
On the other hand, vectorisation operates on the entire array at once without using explicit loops, making the code shorter and more efficient. NumPy is faster because it uses optimized C code internally, avoids the overhead of Python loops, stores data in contiguous memory for better performance, and can perform operations in parallel.
